sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latex-beamer
  texlive-science
script:
- bash .ci/travis/make_all.sh
after_success:
- bash .ci/travis/zip_pdfs.sh
deploy:
  provider: releases
  api_key: 
    secure: nGqBiDrTL7nI1cqLYG4ReMJjKGhws2bzEUhr+B46QesMif3jAlHUIezioJX3yEMKF78xTE6kf6Iye36vaTHIg0uJMmZV9IOWhxEfU54r2rwcoH//WbcPzHiICojwVTQUqpourpsDCRMcT2xAM7rMTOQA63reafQapAdXy9NCrXvtt73GS8PCUOh3KFDRisgonkv0OD/sVMLxi30mcKxSvHQ0tgJ/ctMtskCTBkk33qickbW6B+8IbLx6X85CVXkZG/oo+gtTf73B85OYOD+3bII3q9p/xyJS72P7S42qs+kF16b1+/2gdZwrnsEEhG9F78JFL+ZLqdcWthqwtLx9asNYaojVtaWqpHP6+wxTP2L2OemlHSPaSyDq+OBSHaWWrhjgQ6xY+tvwje0u4vYFqF4HNj9jdVo5gOds9XAkkAzvXQwfvj2FCzLJwvBwv1CHtFGObONlJac282kUjIgfbR1AbPxYVZVMSSJkI38ehaXsoowbc6VdzxGIGyOrOzJQSzItWqE0ui6OzA7lqs6PihV79DwbQNSGFWx1YyPdHm9fhHaCyZ6V5cgfDQ1gswQjkU4tL2MVDrc0V1TrP96uJVQkNXkjZNrbTjZ/gEMXo+SwWIqeITmDwwubLEE43uALIH26e7MdGmH4fmihfWB/Hv4J1snseJpihJDzD9Cbc8M=
  file_glob: true
  file:
  - "./notes/**/tutorial_*.slides.pdf"
  - "./notes/**/tutorial_*.notes.pdf"
  - "./tutorial_*.zip"
  skip_cleanup: true
  on:
    repo: kashefy/mi2notes
    branch: master

